
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 123
#define YY_END_OF_BUFFER 124
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[463] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      124,  122,    7,    9,    8,    6,   85,  122,  121,  106,
      103,  122,   60,   61,  101,   99,   67,  100,   68,  102,
       77,   77,   88,   66,   84,   82,   83,   87,  122,  121,
      121,   64,   65,  105,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
       62,  104,   63,   86,  123,    3,    4,  123,   94,    0,
       74,    0,  121,  117,   95,  114,    0,    0,    0,    0,
      112,   97,  110,   98,  111,   89,    0,   80,    2,    1,
      113,   80,   76,    0,    0,   80,    0,   77,    0,    0,

       77,    0,   71,  107,   93,   91,   92,  108,    0,    0,
      121,  121,  116,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,   21,  121,  121,  121,  121,  121,  121,
      121,  121,   17,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  115,   96,    5,   74,    0,    0,    0,   73,
       73,    0,    0,   90,   69,   80,   80,    0,    0,   80,
       80,    0,   76,   76,    0,    0,   79,    0,   80,   80,
        0,   78,   76,   77,    0,   77,  118,  119,  109,    0,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,

      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
       12,  121,  121,  121,   42,  121,  121,   13,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,   44,  121,  121,  121,    0,    0,
        0,    0,    0,   80,   80,   80,    0,    0,   80,   80,
       79,   79,    0,   80,   80,   80,    0,    0,    0,    0,
       78,   78,    0,    0,   76,    0,   77,    0,  120,    0,
      121,  121,  121,  121,  121,  121,   30,   35,  121,   45,
      121,  121,  121,  121,  121,   31,   36,  121,  121,  121,
      121,   22,  121,  121,  121,  121,   52,  121,   75,  121,

      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
       24,  121,  121,   72,   49,  121,  121,   80,   80,    0,
       80,   80,    0,   80,    0,   80,    0,    0,    0,   81,
       81,    0,  121,  121,  121,  121,  121,   25,   40,   50,
       55,  121,  121,  121,  121,   46,   56,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,   43,  121,  121,
       58,  121,  121,   29,  121,  121,   59,   80,    0,   80,
       80,    0,   80,   80,    0,   81,   81,   81,    0,    0,
      121,    0,  121,   15,  121,  121,  121,   26,  121,  121,
      121,   32,  121,  121,   57,  121,  121,  121,   33,   38,

       48,  121,   14,  121,   34,  121,  121,   80,    0,   80,
        0,   81,    0,   81,    0,    0,    0,  121,   20,  121,
       16,   41,   51,  121,  121,  121,   18,   23,  121,  121,
      121,  121,  121,   81,    0,    0,    0,    0,   10,   11,
      121,  121,  121,  121,   53,  121,  121,   54,   70,    0,
      121,  121,   47,   28,  121,   39,   27,   37,  121,  121,
       19,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   24,   24,   24,   24,   25,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   33,   35,   36,   37,
        9,    9,    9,    9,    9,   38,    9,   39,   40,   41,
        9,    9,    9,    9,    9,    9,    9,   42,    9,    9,
       43,   44,   45,   46,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,    9,   57,   58,   59,   60,
       61,   62,    9,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    3,    4,    1,
        1,    5,    1,    1,    1,    1,    1,    1,    6,    1,
        7,    7,    7,    7,    7,    1,    1,    1,    1,    1,
        1,    1,    7,    7,    7,    7,    7,    8,    4,    4,
        9,    4,    1,    1,    1,    1,    9,    7,    7,    7,
        7,    7,    7,    4,    4,    4,    4,    8,    4,    4,
        4,    9,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[471] =
    {   0,
        0,    0,  959,  958,   73,   74,    0,    0,    0,    0,
      960,  963,  963,  963,  963,  963,  930,   70,    0,  929,
       68,  913,  963,   78,  927,   69,  963,   65,   80,   71,
       96,  147,  929,  963,   64,  925,   77,  963,   84,  892,
      894,  963,  963,  922,   59,   65,   81,   61,   86,  102,
      889,  114,  888,  109,   93,  896,  121,  125,  886,  891,
      963,   80,  963,  963,  963,  963,  963,  925,  963,  108,
      963,  198,    0,  963,  963,  963,  932,  204,  175,  913,
      963,  963,  963,  963,  963,  963,  923,  249,  963,  963,
      963,  254,  289,  329,   89,  963,  213,  963,  922,  296,

      308,  336,  963,  911,  963,  963,  963,  166,  184,  872,
      872,  876,  963,  872,  871,  873,  881,  867,  137,  883,
      882,  869,  875,  861,  862,  859,  859,  865,  862,  860,
      857,  854,    0,  856,  139,  856,  845,  841,  843,  848,
      136,  844,  827,  822,   64,  809,  814,  809,  151,  175,
      106,  812,  963,  963,  963,  200,  205,  348,  365,  963,
      854,  271,  372,  963,  963,    0,  963,  381,  389,  416,
      963,  399,    0,  963,  407,  423,  369,  434,  427,  465,
        0,  463,  451,    0,  470,  484,  963,  963,  836,  812,
      814,  814,  796,  808,  801,  810,  804,  803,  804,  790,

      787,  153,  791,  789,  785,  777,  772,  759,  774,  773,
        0,  758,   79,  747,  759,  756,  753,    0,  734,  728,
      717,  718,  719,  710,  711,  708,  716,  709,  689,  697,
      682,  684,  684,  690,    0,  689,  690,  679,  505,  222,
      512,  724,  516,  507,  545,    0,  529,  550,  526,  583,
      564,  963,  218,  963,  446,  566,  602,  241,  170,  192,
      591,  609,  621,  632,    0,  633,    0,  638,  963,  672,
      668,  658,  633,  630,  640,  632,    0,    0,  633,    0,
      623,  621,  628,  617,  624,    0,    0,  612,  612,  594,
      583,    0,  595,  572,  585,  568,    0,  552,    0,  568,

      567,  562,  556,  546,  536,  544,  547,  532,  544,  538,
        0,  513,  514,    0,    0,  497,  507,  495,  644,  653,
      644,  677,  682,    0,  687,  692,  275,  287,  697,  690,
      728,  494,  504,  536,  499,  478,  474,    0,    0,    0,
        0,  460,  461,  463,  463,  453,    0,  437,  419,  419,
      424,  424,  412,  396,  410,  400,  389,    0,  393,  377,
        0,  380,  371,  369,  370,  369,    0,    0,  708,  735,
        0,  746,  766,    0,  773,  963,  727,  778,  783,  363,
      399,  369,  351,    0,  340,  332,  320,    0,  315,  308,
      325,    0,  325,  326,    0,  316,  315,  298,    0,    0,

        0,  309,    0,  285,    0,  293,  286,    0,  793,    0,
      805,    0,  810,  820,  288,  299,  287,  258,    0,  263,
        0,    0,    0,  249,  252,  249,    0,    0,  246,  235,
      227,  221,  228,    0,  825,  216,  214,  221,    0,    0,
      194,  195,  203,  201,    0,  194,  183,    0,  963,  207,
      179,  162,    0,    0,  138,    0,    0,    0,   99,   74,
        0,  963,  872,  881,  887,  896,  900,   80,  905,  908
    } ;

static const flex_int16_t yy_def[471] =
    {   0,
      462,    1,  463,  463,  463,  463,  463,  463,  463,  463,
      462,  462,  462,  462,  462,  462,  462,  464,  465,  462,
      462,  466,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  465,
      465,  462,  462,  462,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  464,
      462,  464,  465,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  467,  462,

       32,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      465,  465,  462,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  462,  462,  462,  464,  464,  464,  464,  462,
      462,  462,  462,  462,  462,   88,  462,  462,  462,  462,
      462,  462,   93,  462,  462,  462,  462,  462,  462,  462,
      468,  469,   93,  101,  462,  101,  462,  462,  462,  462,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,

      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  464,  464,
      462,  462,  462,  462,  462,  170,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  180,  462,  470,  462,  468,
      469,  462,  462,  261,  183,  462,  186,  462,  462,  462,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,

      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  462,  245,  462,
      462,  250,  462,  256,  462,  256,  470,  470,  462,  462,
      462,  462,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  319,  462,  319,
      322,  462,  322,  326,  462,  462,  462,  331,  462,  462,
      465,  462,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,

      465,  465,  465,  465,  465,  465,  465,  370,  462,  373,
      462,  378,  462,  378,  462,  462,  462,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  414,  462,  462,  462,  462,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  462,  462,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,    0,  462,  462,  462,  462,  462,  462,  462,  462
    } ;

static const flex_int16_t yy_nxt[1039] =
    {   0,
       12,   13,   14,   15,   12,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   32,   32,   32,   33,   34,   35,   36,   37,
       38,   39,   19,   19,   40,   19,   41,   19,   19,   19,
       19,   19,   42,   12,   43,   44,   19,   45,   46,   47,
       48,   49,   50,   51,   19,   52,   19,   53,   19,   54,
       19,   55,   56,   57,   58,   19,   59,   60,   19,   19,
       19,   61,   62,   63,   64,   67,   67,   71,   75,   79,
       79,   79,   84,   79,   82,   89,  258,   68,   68,  109,
       90,  104,  105,   85,   86,   80,   76,   83,   87,   91,

       88,   88,   88,   88,   88,  107,  108,  114,  153,  177,
      177,  226,  123,   72,   92,   71,   93,   93,   93,   93,
       94,  124,  115,  110,  461,  116,  227,  117,  119,   95,
       96,   97,   96,   98,  118,  120,  293,   99,  121,  294,
      140,  122,  100,  125,   95,  126,   96,   97,   96,  128,
      460,   72,  154,   98,  127,  141,  137,  129,  142,  130,
      138,  236,  131,  237,   99,   92,  133,  101,  101,  101,
      101,  101,  134,  135,  139,  144,   79,   79,   79,  149,
       79,   96,   97,   96,   98,  145,  146,  150,  147,  109,
      148,  221,   80,  102,  188,  189,  222,   96,   97,   96,

      198,  199,  214,  215,   98,  156,  231,   71,  459,  157,
      263,   77,   71,  232,  458,  161,  282,  283,  158,  158,
      158,  159,  233,  110,  162,  162,  162,  163,  178,   71,
      178,  263,  263,  179,  180,  180,  180,  180,  251,  251,
      234,   72,  457,   72,  235,   96,  157,  456,   72,  455,
      157,  454,   77,  263,  453,  452,   77,  157,  451,   96,
      157,  450,  157,   77,  253,   72,   77,  449,   77,  166,
      166,  166,  166,  166,  170,  170,  170,  170,  170,  448,
      447,  263,  160,  167,  168,  167,  446,  328,  171,  172,
      171,  241,  241,  241,  241,  169,  445,  444,  443,  167,

      168,  167,  263,  442,  171,  172,  171,   92,  441,  173,
      173,  173,  173,   94,  440,  263,  183,  183,  183,  183,
       94,  328,  439,   96,   97,   96,  174,  462,  184,  184,
      184,  184,  184,  328,  438,  175,  263,  437,  436,   96,
       97,   96,  100,  433,  432,  431,  174,   92,  462,   94,
       94,   94,   94,   94,  185,   71,  186,  186,  186,  186,
      186,  430,  429,   96,   97,   96,  428,  427,  239,  239,
      239,  239,   71,  426,  425,  176,  424,  423,  422,   96,
       97,   96,  176,  160,  421,  240,  240,  240,  240,  251,
      251,   72,  242,  242,  242,  242,  243,  420,  243,  419,

      418,  244,  245,  245,  245,  245,  252,  417,   72,  166,
      166,  166,  166,  166,  248,  253,  248,  416,  415,  249,
      250,  250,  250,  250,  407,  406,  252,  173,  173,  173,
      173,   94,  405,  404,  403,  169,  246,  246,  246,  246,
      246,  402,  401,   94,   94,   94,   94,   94,  400,  399,
      171,  172,  171,  175,  179,  180,  180,  180,  180,  398,
      397,  254,  247,  254,  255,  396,  171,  172,  171,  176,
      259,  265,  265,  265,  265,  395,  394,  254,  393,  254,
      254,  260,  254,  392,  255,  256,  256,  256,  256,  256,
      184,  184,  184,  184,  184,  391,  254,  266,  254,  254,

      262,  254,  255,  263,  267,  267,  267,  267,  267,  264,
      390,  257,   71,  389,  388,  254,  185,  254,  387,  386,
      262,  385,  255,  160,  263,  240,  240,  240,  240,  167,
      268,  167,  242,  242,  242,  242,  244,  245,  245,  245,
      245,  167,  384,  167,  318,  167,  383,  167,   72,  246,
      246,  246,  246,  246,  382,  381,  380,  167,  367,  167,
      171,  366,  171,  321,  318,  319,  319,  319,  319,  319,
      249,  250,  250,  250,  250,  247,  171,  365,  171,  167,
      364,  167,  318,  321,  251,  251,  324,  324,  324,  324,
      324,  320,  363,  362,  361,  167,  360,  167,  259,  359,

      358,  252,  318,  322,  322,  322,  322,  322,  357,  260,
      253,  356,  325,  355,  354,  353,  259,  171,  352,  171,
      321,  252,  326,  326,  326,  326,  326,  259,  262,  323,
      351,  263,  350,  171,  349,  171,  329,  264,  329,  462,
      321,  330,  331,  331,  331,  331,  348,  347,  262,  263,
      462,  346,  263,  265,  265,  265,  265,   94,  267,  267,
      267,  267,  267,  314,  368,  368,  368,  368,  368,  462,
      263,  345,  462,  370,  370,  370,  370,  370,  171,  266,
      171,  344,  343,  342,  268,  341,  340,  339,  338,  462,
      369,  337,  336,  462,  171,  335,  171,  371,  371,  371,

      371,  371,  373,  373,  373,  373,  373,  324,  324,  324,
      324,  324,  374,  374,  374,  374,  374,  330,  331,  331,
      331,  331,  334,  372,  376,  333,  376,  377,  368,  368,
      368,  368,  368,  325,  332,  160,  317,  316,  375,  315,
      376,  314,  376,  313,  312,  311,  310,  377,  378,  378,
      378,  378,  378,  309,  369,  408,  408,  408,  408,  408,
      308,  376,  376,  376,  376,  377,  371,  371,  371,  371,
      371,  307,  306,  305,  379,  304,  303,  376,  376,  376,
      376,  409,  302,  301,  300,  377,  410,  410,  410,  410,
      410,  299,  372,  374,  374,  374,  374,  374,  412,  412,

      412,  412,  412,  414,  414,  414,  414,  414,  298,  297,
      296,  295,  411,  408,  408,  408,  408,  408,  292,  375,
      291,  290,  289,  288,  413,  410,  410,  410,  410,  410,
      412,  412,  412,  412,  412,  287,  286,  285,  284,  409,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      281,  411,  280,  279,  278,  277,  413,  276,  275,  274,
      273,  272,  271,  270,  269,  160,  435,  238,  230,  229,
      228,  435,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   70,  225,   70,   70,   70,   70,   70,   70,   70,
       73,  224,  223,   73,   73,   73,   77,  220,   77,   77,

      219,   77,   77,   77,   77,  182,  182,  261,  218,  217,
      261,  261,  261,  261,  327,  216,  327,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  197,  196,  195,  194,  193,  192,  191,  190,  187,
      181,  165,  164,  160,  155,  152,  151,  143,  136,  132,
      113,  112,  111,  106,  103,   81,   78,   74,   69,  462,
       66,   66,   11,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,

      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462
    } ;

static const flex_int16_t yy_chk[1039] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    6,   18,   21,   24,
       24,   24,   28,   24,   26,   30,  468,    5,    6,   39,
       30,   35,   35,   28,   28,   24,   21,   26,   29,   30,

       29,   29,   29,   29,   29,   37,   37,   45,   62,   95,
       95,  145,   48,   18,   31,   70,   31,   31,   31,   31,
       31,   48,   45,   39,  460,   46,  145,   46,   47,   31,
       31,   31,   31,   31,   46,   47,  213,   31,   47,  213,
       55,   47,   31,   49,   31,   49,   31,   31,   31,   50,
      459,   70,   62,   31,   49,   55,   54,   50,   55,   50,
       54,  151,   50,  151,   31,   32,   52,   32,   32,   32,
       32,   32,   52,   52,   54,   57,   79,   79,   79,   58,
       79,   32,   32,   32,   32,   57,   57,   58,   57,  109,
       57,  141,   79,   32,  108,  108,  141,   32,   32,   32,

      119,  119,  135,  135,   32,   72,  149,  156,  455,   72,
      259,   78,  157,  149,  452,   78,  202,  202,   72,   72,
       72,   72,  150,  109,   78,   78,   78,   78,   97,  240,
       97,  259,  260,   97,   97,   97,   97,   97,  253,  253,
      150,   72,  451,  156,  150,  450,   72,  447,  157,  446,
       72,  444,   78,  260,  443,  442,   78,   72,  441,  438,
       72,  437,   72,   78,  253,  240,   78,  436,   78,   88,
       88,   88,   88,   88,   92,   92,   92,   92,   92,  433,
      432,  258,  162,   88,   88,   88,  431,  258,   92,   92,
       92,  162,  162,  162,  162,   88,  430,  429,  426,   88,

       88,   88,  258,  425,   92,   92,   92,   93,  424,   93,
       93,   93,   93,   93,  420,  327,  100,  100,  100,  100,
      100,  327,  418,   93,   93,   93,   93,  328,  101,  101,
      101,  101,  101,  328,  417,   93,  327,  416,  415,   93,
       93,   93,  100,  407,  406,  404,   93,   94,  328,   94,
       94,   94,   94,   94,  101,  158,  102,  102,  102,  102,
      102,  402,  398,   94,   94,   94,  397,  396,  158,  158,
      158,  158,  159,  394,  393,   94,  391,  390,  389,   94,
       94,   94,  102,  163,  387,  159,  159,  159,  159,  177,
      177,  158,  163,  163,  163,  163,  168,  386,  168,  385,

      383,  168,  168,  168,  168,  168,  177,  382,  159,  169,
      169,  169,  169,  169,  172,  177,  172,  381,  380,  172,
      172,  172,  172,  172,  366,  365,  177,  175,  175,  175,
      175,  175,  364,  363,  362,  169,  170,  170,  170,  170,
      170,  360,  359,  176,  176,  176,  176,  176,  357,  356,
      170,  170,  170,  175,  178,  178,  178,  178,  178,  355,
      354,  179,  170,  179,  179,  353,  170,  170,  170,  176,
      182,  183,  183,  183,  183,  352,  351,  179,  350,  179,
      255,  182,  255,  349,  179,  180,  180,  180,  180,  180,
      185,  185,  185,  185,  185,  348,  255,  183,  255,  180,

      182,  180,  180,  182,  186,  186,  186,  186,  186,  182,
      346,  180,  239,  345,  344,  180,  185,  180,  343,  342,
      182,  337,  180,  241,  182,  239,  239,  239,  239,  318,
      186,  318,  241,  241,  241,  241,  243,  243,  243,  243,
      243,  244,  336,  244,  244,  318,  335,  318,  239,  247,
      247,  247,  247,  247,  334,  333,  332,  244,  317,  244,
      249,  316,  249,  249,  244,  245,  245,  245,  245,  245,
      248,  248,  248,  248,  248,  247,  249,  313,  249,  245,
      312,  245,  245,  249,  251,  251,  256,  256,  256,  256,
      256,  245,  310,  309,  308,  245,  307,  245,  261,  306,

      305,  251,  245,  250,  250,  250,  250,  250,  304,  261,
      251,  303,  256,  302,  301,  300,  262,  250,  298,  250,
      250,  251,  257,  257,  257,  257,  257,  262,  261,  250,
      296,  261,  295,  250,  294,  250,  263,  261,  263,  264,
      250,  263,  263,  263,  263,  263,  293,  291,  261,  262,
      264,  290,  261,  266,  266,  266,  266,  266,  268,  268,
      268,  268,  268,  289,  319,  319,  319,  319,  319,  264,
      262,  288,  264,  320,  320,  320,  320,  320,  321,  266,
      321,  285,  284,  283,  268,  282,  281,  279,  276,  264,
      319,  275,  274,  264,  321,  273,  321,  322,  322,  322,

      322,  322,  323,  323,  323,  323,  323,  325,  325,  325,
      325,  325,  326,  326,  326,  326,  326,  329,  329,  329,
      329,  329,  272,  322,  330,  271,  330,  330,  369,  369,
      369,  369,  369,  325,  270,  242,  238,  237,  326,  236,
      330,  234,  330,  233,  232,  231,  230,  330,  331,  331,
      331,  331,  331,  229,  369,  370,  370,  370,  370,  370,
      228,  377,  331,  377,  331,  331,  372,  372,  372,  372,
      372,  227,  226,  225,  331,  224,  223,  377,  331,  377,
      331,  370,  222,  221,  220,  331,  373,  373,  373,  373,
      373,  219,  372,  375,  375,  375,  375,  375,  378,  378,

      378,  378,  378,  379,  379,  379,  379,  379,  217,  216,
      215,  214,  373,  409,  409,  409,  409,  409,  212,  375,
      210,  209,  208,  207,  378,  411,  411,  411,  411,  411,
      413,  413,  413,  413,  413,  206,  205,  204,  203,  409,
      414,  414,  414,  414,  414,  435,  435,  435,  435,  435,
      201,  411,  200,  199,  198,  197,  413,  196,  195,  194,
      193,  192,  191,  190,  189,  161,  414,  152,  148,  147,
      146,  435,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  464,  144,  464,  464,  464,  464,  464,  464,  464,
      465,  143,  142,  465,  465,  465,  466,  140,  466,  466,

      139,  466,  466,  466,  466,  467,  467,  469,  138,  137,
      469,  469,  469,  469,  470,  136,  470,  134,  132,  131,
      130,  129,  128,  127,  126,  125,  124,  123,  122,  121,
      120,  118,  117,  116,  115,  114,  112,  111,  110,  104,
       99,   87,   80,   77,   68,   60,   59,   56,   53,   51,
       44,   41,   40,   36,   33,   25,   22,   20,   17,   11,
        4,    3,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,

      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <iostream>
#include <vector>
#include <getopt.h>
#include "parser.tab.h"

using namespace std;

void error_lexer();


typedef struct
{
  char* name;
  int count;
}token_struct;

vector<token_struct> tokens_found;
int line_num;

#line 848 "lex.yy.c"

#line 850 "lex.yy.c"

#define INITIAL 0
#define single_begin 1
#define multi_begin 2
#define char_start 3
#define char_to_end 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 87 "lexer.l"

#line 1073 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 463 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 963 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 88 "lexer.l"
BEGIN(single_begin);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "lexer.l"
BEGIN(multi_begin);
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 90 "lexer.l"
{ line_num++; BEGIN(INITIAL); }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 91 "lexer.l"
{ line_num++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 92 "lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "lexer.l"
{ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 95 "lexer.l"
{ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 96 "lexer.l"
{ }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 97 "lexer.l"
{ line_num++; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(abstract)", 32); /* printf("TOKEN: %s\n",yytext); */ return ABSTRACT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(continue)", 32); /* printf("TOKEN: %s\n",yytext); */ return CONTINUE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(for)", 32); /* printf("TOKEN: %s\n",yytext); */ return FOR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(new)", 32); /* printf("TOKEN: %s\n",yytext); */ return NEW; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 103 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(switch)", 32); /* printf("TOKEN: %s\n",yytext); */ return SWITCH; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(assert)", 32); /* printf("TOKEN: %s\n",yytext); */ return ASSERT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(default)", 32); /* printf("TOKEN: %s\n",yytext); */ return DEFAULT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(if)", 32); /* printf("TOKEN: %s\n",yytext); */ return IF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 107 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(package)", 32); /* printf("TOKEN: %s\n",yytext); */ return PACKAGE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 108 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(synchronized)", 32); /* printf("TOKEN: %s\n",yytext); */ return SYNCHRONIZED; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 109 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(boolean)", 32); /* printf("TOKEN: %s\n",yytext); */ return BOOLEAN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 110 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(do)", 32); /* printf("TOKEN: %s\n",yytext); */ return DO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 111 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(goto)", 32); /* printf("TOKEN: %s\n",yytext); */ return GOTO; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(private)", 32); /* printf("TOKEN: %s\n",yytext); */ return PRIVATE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 113 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(this)", 32); /* printf("TOKEN: %s\n",yytext); */ return THIS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 114 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(break)", 32); /* printf("TOKEN: %s\n",yytext); */ return BREAK; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 115 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(double)", 32); /* printf("TOKEN: %s\n",yytext); */ return DOUBLE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 116 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(implements)", 32); /* printf("TOKEN: %s\n",yytext); */ return IMPLEMENTS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 117 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(protected)", 32); /* printf("TOKEN: %s\n",yytext); */ return PROTECTED; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 118 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(throw)", 32); /* printf("TOKEN: %s\n",yytext); */ return THROW; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(byte)", 32); /* printf("TOKEN: %s\n",yytext); */ return BYTE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 120 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(else)", 32); /* printf("TOKEN: %s\n",yytext); */ return ELSE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 121 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(import)", 32); /* printf("TOKEN: %s\n",yytext); */ return IMPORT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(public)", 32); /* printf("TOKEN: %s\n",yytext); */ return PUBLIC; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 123 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(throws)", 32); /* printf("TOKEN: %s\n",yytext); */ return THROWS; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 124 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(case)", 32); /* printf("TOKEN: %s\n",yytext); */ return CASE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 125 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(enum)", 32); /* printf("TOKEN: %s\n",yytext); */ return ENUM; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 126 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(instanceof)", 32); /* printf("TOKEN: %s\n",yytext); */ return INSTANCEOF; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 127 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(return)", 32); /* printf("TOKEN: %s\n",yytext); */ return RETURN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 128 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(transient)", 32); /* printf("TOKEN: %s\n",yytext); */ return TRANSIENT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 129 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(catch)", 32); /* printf("TOKEN: %s\n",yytext); */ return CATCH; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 130 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(extends)", 32); /* printf("TOKEN: %s\n",yytext); */ return EXTENDS; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 131 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(int)", 32); /* printf("TOKEN: %s\n",yytext); */ return INT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 132 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(short)", 32); /* printf("TOKEN: %s\n",yytext); */ return SHORT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 133 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(try)", 32); /* printf("TOKEN: %s\n",yytext); */ return TRY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 134 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(char)", 32); /* printf("TOKEN: %s\n",yytext); */ return CHAR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 135 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(final)", 32); /* printf("TOKEN: %s\n",yytext); */ return FINAL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 136 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(interface)", 32); /* printf("TOKEN: %s\n",yytext); */ return INTERFACE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 137 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(static)", 32); /* printf("TOKEN: %s\n",yytext); */ return STATIC; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 138 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(void)", 32); /* printf("TOKEN: %s\n",yytext); */ return VOID; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 139 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(class)", 32); /* printf("TOKEN: %s\n",yytext); */ return CLASS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 140 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(finally)", 32); /* printf("TOKEN: %s\n",yytext); */ return FINALLY; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 141 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(long)", 32); /* printf("TOKEN: %s\n",yytext); */ return LONG; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 142 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(strictfp)", 32); /* printf("TOKEN: %s\n",yytext); */ return STRICTFP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 143 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(volatile)", 32); /* printf("TOKEN: %s\n",yytext); */ return VOLATILE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 144 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(const)", 32); /* printf("TOKEN: %s\n",yytext); */ return CONST; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 145 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(float)", 32); /* printf("TOKEN: %s\n",yytext); */ return FLOAT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 146 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(native)", 32); /* printf("TOKEN: %s\n",yytext); */ return NATIVE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 147 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(super)", 32); /* printf("TOKEN: %s\n",yytext); */ return SUPER; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 148 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "KEYWORD(while)", 32); /* printf("TOKEN: %s\n",yytext); */ return WHILE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 150 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( ( )", 32); /* printf("TOKEN: %s\n",yytext); */ return LEFT_PAREN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 151 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( ) )", 32); /* printf("TOKEN: %s\n",yytext); */ return RIGHT_PAREN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 152 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( { )", 32); /* printf("TOKEN: %s\n",yytext); */ return LEFT_CURLY; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 153 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( } )", 32); /* printf("TOKEN: %s\n",yytext); */ return RIGHT_CURLY; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 154 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( [ )", 32); /* printf("TOKEN: %s\n",yytext); */ return LEFT_SQUARE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 155 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( ] )", 32); /* printf("TOKEN: %s\n",yytext); */ return RIGHT_SQUARE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 156 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( ; )", 32); /* printf("TOKEN: %s\n",yytext); */ return SEMI_COLON; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 157 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( , )", 32); /* printf("TOKEN: %s\n",yytext); */ return COMMA; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 158 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( . )", 32); /* printf("TOKEN: %s\n",yytext); */ return DOT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 159 "lexer.l"
{ yylval.str = (char*)malloc(24); strncpy(yylval.str, "SEPARATOR( ... )", 24); /* printf("TOKEN: %s\n",yytext); */ return TRIPLE_DOT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 160 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( @ )", 32); /* printf("TOKEN: %s\n",yytext); */ return AT_RATE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 161 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "SEPARATOR( :: )", 32); /* printf("TOKEN: %s\n",yytext); */ return DOUBLE_COLON; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 163 "lexer.l"
{ if(strncmp(yytext, "true", 32) == 0) { yylval.truth = true;} else { yylval.truth = false;} /* printf("TOKEN: %s\n",yytext); */ return BOOLEAN_LIT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 164 "lexer.l"
{ yylval.character = yytext[1]; /* printf("TOKEN: %s\n",yytext); */ return CHAR_LIT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 165 "lexer.l"
{ yylval.str = (char*)malloc(strlen(yytext)+1); yytext[strlen(yytext)-1] = '\0'; strncpy(yylval.str, yytext+1, strlen(yytext)+1); /* printf("TOKEN: %s\n",yytext); */ return STRING_LIT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 166 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "null", 32); /* printf("TOKEN: %s\n",yytext); */ return NULL_LIT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 167 "lexer.l"
{ yylval.integer = strtol(yytext, NULL, 32); /* printf("TOKEN: %s\n",yytext); */ return INTEGER_LIT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 168 "lexer.l"
{ yylval.integer = strtol(yytext, NULL, 10); /* printf("TOKEN: %s\n",yytext); */ return INTEGER_LIT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 169 "lexer.l"
{ yylval.integer = strtol(yytext, NULL, 32); /* printf("TOKEN: %s\n",yytext); */ return INTEGER_LIT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 170 "lexer.l"
{ yylval.integer = strtol(yytext, NULL, 2); /* printf("TOKEN: %s\n",yytext); */ return INTEGER_LIT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 171 "lexer.l"
{ yylval.fraction = strtod(yytext, NULL); /* printf("TOKEN: %s\n",yytext); */ return FLOATING_LIT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 172 "lexer.l"
{ yylval.fraction = strtod(yytext, NULL); /* printf("TOKEN: %s\n",yytext); */ return FLOATING_LIT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 174 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( = )", 32); /* printf("TOKEN: %s\n",yytext); */ return ASSIGN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 175 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( > )", 32); /* printf("TOKEN: %s\n",yytext); */ return GT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 176 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( < )", 32); /* printf("TOKEN: %s\n",yytext); */ return LT; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 177 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( ! )", 32); /* printf("TOKEN: %s\n",yytext); */ return NOT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 178 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( ~ )", 32); /* printf("TOKEN: %s\n",yytext); */ return NEG; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 179 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( ? )", 32); /* printf("TOKEN: %s\n",yytext); */ return TERNARY; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 180 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( : )", 32); /* printf("TOKEN: %s\n",yytext); */ return COLON; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 181 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( -> )", 32); /* printf("TOKEN: %s\n",yytext); */ return POINTER; }
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 182 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( ) -> )", 32); /* printf("TOKEN: %s\n",yytext); */ return RPOINTER; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 183 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( == )", 32); /* printf("TOKEN: %s\n",yytext); */ return EQUAL; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 184 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( >= )", 32); /* printf("TOKEN: %s\n",yytext); */ return GTE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 185 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( <= )", 32); /* printf("TOKEN: %s\n",yytext); */ return LTE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 186 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( != )", 32); /* printf("TOKEN: %s\n",yytext); */ return NOTEQ; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 187 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( && )", 32); /* printf("TOKEN: %s\n",yytext); */ return BAND; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 188 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( || )", 32); /* printf("TOKEN: %s\n",yytext); */ return BOR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 189 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( ++ )", 32); /* printf("TOKEN: %s\n",yytext); */ return INC; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 190 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( -- )", 32); /* printf("TOKEN: %s\n",yytext); */ return DEC; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 191 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( + )", 32); /* printf("TOKEN: %s\n",yytext); */ return ADD; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 192 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( - )", 32); /* printf("TOKEN: %s\n",yytext); */ return SUB; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 193 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( * )", 32); /* printf("TOKEN: %s\n",yytext); */ return MUL; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 194 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( / )", 32); /* printf("TOKEN: %s\n",yytext); */ return DIV; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 195 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( & )", 32); /* printf("TOKEN: %s\n",yytext); */ return LAND; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 196 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( | )", 32); /* printf("TOKEN: %s\n",yytext); */ return LOR; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 197 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( ^ )", 32); /* printf("TOKEN: %s\n",yytext); */ return LXOR; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 198 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( % )", 32); /* printf("TOKEN: %s\n",yytext); */ return MOD; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 199 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( << )", 32); /* printf("TOKEN: %s\n",yytext); */ return LSHIFT; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 200 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( >> )", 32); /* printf("TOKEN: %s\n",yytext); */ return RSHIFT; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 201 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( >>> )", 32); /* printf("TOKEN: %s\n",yytext); */ return RRSHIFT; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 202 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( += )", 32); /* printf("TOKEN: %s\n",yytext); */ return ADDASSN; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 203 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( -= )", 32); /* printf("TOKEN: %s\n",yytext); */ return SUBASSN; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 204 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( *= )", 32); /* printf("TOKEN: %s\n",yytext); */ return MULASSN; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 205 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( /= )", 32); /* printf("TOKEN: %s\n",yytext); */ return DIVASSN; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 206 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( &= )", 32); /* printf("TOKEN: %s\n",yytext); */ return ANDASSN; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 207 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( |= )", 32); /* printf("TOKEN: %s\n",yytext); */ return ORASSN; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 208 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( ^= )", 32); /* printf("TOKEN: %s\n",yytext); */ return XORASSN; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 209 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( %= )", 32); /* printf("TOKEN: %s\n",yytext); */ return MODASSN; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 210 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( <<= )", 32); /* printf("TOKEN: %s\n",yytext); */ return LSHIFTASSN; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 211 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( >>= )", 32); /* printf("TOKEN: %s\n",yytext); */ return RSHIFTASSN; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 212 "lexer.l"
{ yylval.str = (char*)malloc(32); strncpy(yylval.str, "OPERATOR( >>>= )", 32); /* printf("TOKEN: %s\n",yytext); */ return RRSHIFTASSN; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 214 "lexer.l"
{ yylval.str = (char*)malloc(strlen(yytext)+32); snprintf(yylval.str, strlen(yytext)+32, "IDENTIFIER( %s )", yytext); /* printf("TOKEN: %s\n",yytext); */ return IDENTIFIER; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 216 "lexer.l"
{ error_lexer(); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 219 "lexer.l"
ECHO;
	YY_BREAK
#line 1749 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(single_begin):
case YY_STATE_EOF(multi_begin):
case YY_STATE_EOF(char_start):
case YY_STATE_EOF(char_to_end):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 463 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 463 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 462);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 219 "lexer.l"


void error_lexer()
{
  fprintf(stderr, "ERROR: Unmatched character %s at line number %d\n", yytext, line_num);
  exit(-1);
}

void debug(const char* message)
{
  return;
  int found = 0;
  int count = 0;
  for (vector<token_struct>::iterator one_token = tokens_found.begin(); one_token != tokens_found.end(); ++one_token)
  {
    if(strncmp("int",(*one_token).name,32) == 0)
    {
      count = (*one_token).count;
      found = 1;
      break;
    }
  }
  if(found)
  {
    printf("%s:  Found token: %20s at line %d. Int count: %d\n", message, yytext, line_num+1, count);
  }
  else
  {
    printf("%s:  Found token: %20s at line %d. Int not found\n", message, yytext, line_num+1);
  }
}

int is_keyword(char* token)
{
  const char* keyword_list[] = { "abstract",   "continue",   "for",          "new",         "switch",
                          "assert",     "default",    "if",           "package",     "synchronized",
                          "boolean",    "do",         "goto",         "private",     "this",
                          "break",      "double",     "implements",   "protected",   "throw",
                          "byte",       "else",       "import",       "public",      "throws",
                          "case",       "enum",       "instanceof",   "return",      "transient",
                          "catch",      "extends",    "int",          "short",       "try",
                          "char",       "final",      "interface",    "static",      "void",
                          "class",      "finally",    "long",         "strictfp",    "volatile",
                          "const",      "float",      "native",       "super",       "while"          };

  for(int i = 0; i < 50; i++)
  {
    if(!strncmp(token, keyword_list[i], strlen(token)) && strlen(token) == strlen(keyword_list[i]))
    {
      return 1;
    }
  }
  return 0;
}


int yywrap()
{
  return 1;
}

